### ISSUE TITLE
problem to install the conda environment required for gspa

### ISSUE THREAD

**Issue by ERIGR** [henrycousins/gspa#1]
Hi, I'm very interested by the concept of gspa. I want to use this program on my own data. However, I failed to install the conda environment needed to run gspa easily. I use the environment.yml file that you have provided to generate the conda environment. I got the follow error message when running the command :  conda env create -f environment.yaml

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - freetype==2.10.4=ha233b18_0
  - certifi==2021.5.30=py37hecd8cb5_0
  - libsodium==1.0.18=h1de35cc_0
  - lz4-c==1.9.3=h23ab428_0
  - zeromq==4.3.4=h23ab428_0
  - libwebp-base==1.2.0=h9ed2024_0
  - setuptools==52.0.0=py37hecd8cb5_0
  - intel-openmp==2021.2.0=hecd8cb5_564
  - scikit-learn==0.24.2=py37hb2f4e1b_0
  - mkl_random==1.2.1=py37hb2f4e1b_2
  - llvm-openmp==10.0.0=h28b9765_0
  - numpy==1.20.2=py37h4b4dc7a_0
  - zlib==1.2.11=h1de35cc_3
  - mkl_fft==1.3.0=py37h4a7008c_2
  - pandas==1.2.4=py37h23ab428_0
  - jupyter_core==4.7.1=py37hecd8cb5_0
  - pillow==8.2.0=py37h5270095_0
  - scipy==1.6.2=py37hd5f7400_1
  - xz==5.2.5=h1de35cc_0
  - jpeg==9b=he5867d9_2
  - pyzmq==20.0.0=py37h23ab428_1
  - openssl==1.1.1k=h9ed2024_0
  - kiwisolver==1.3.1=py37h23ab428_0
  - matplotlib==3.3.4=py37hecd8cb5_0
  - mkl-service==2.3.0=py37h9ed2024_1
  - libtiff==4.2.0=h87d7836_0
  - lcms2==2.12=hf1fd2bf_0
  - tornado==6.1=py37h9ed2024_0
  - pip==21.1.1=py37hecd8cb5_0
  - six==1.15.0=py37hecd8cb5_0
  - matplotlib-base==3.3.4=py37h8b3ea08_0
  - appnope==0.1.2=py37hecd8cb5_1001
  - libpng==1.6.37=ha441bb4_0
  - jedi==0.18.0=py37hecd8cb5_1
  - ncurses==6.2=h0a44026_1
  - python==3.7.10=h88f2d9e_0
  - libffi==3.3=hb1e8313_2
  - ca-certificates==2021.5.25=hecd8cb5_1
  - numpy-base==1.20.2=py37he0bd621_0
  - readline==8.1=h9ed2024_0
  - sqlite==3.35.4=hce871da_0
  - zstd==1.4.9=h322a384_0
  - ipython==7.24.1=py37h85f7c60_0
  - libgfortran==3.0.1=h93005f0_2
  - tk==8.6.10=hb0a8c7a_0
  - mkl==2021.2.0=hecd8cb5_269

could you provide an updated conda environment yml file in order to install gspa ?

Thanks !

**Comment by henrycousins** [comment]
Thanks for bringing this up. I don’t have the issue myself but think it could be an operating system problem. Here are a few things to try: (1) install dependencies directly using conda or pip or (2) try importing the .yml file directly in Anaconda Navigator. Alternatively, (3) I added a version of the .yml file at “environments/environment_backup.yml” with some package version identifiers removed, which is less stringent about dependency versions but may be more flexible to install.
